/**
 * Virtual Showroom data (Premium-tier flagship demo).
 *
 * Image contract: /images/showroom/{sceneSlug}-{treatmentSlug}.jpg
 * All images 2528x1696 (3:2). 6 scenes x 5 treatment states = 30 files,
 * generated by the asset pipeline; this module is the single source of
 * truth for slugs, display copy, and paths.
 *
 * ZERO em dashes in any user-facing string (CLAUDE.md Copy Writing Rule).
 */

export interface ShowroomScene {
  slug: string;
  name: string;
  /** One-line room descriptor in Jim's voice. */
  room: string;
}

export interface ShowroomTreatment {
  slug: string;
  name: string;
  /** One-line blurb shown under the treatment pills. */
  blurb: string;
}

export const SHOWROOM_IMAGE_WIDTH = 2528;
export const SHOWROOM_IMAGE_HEIGHT = 1696;

export const SHOWROOM_SCENES: ShowroomScene[] = [
  {
    slug: "coastal-living",
    name: "Coastal Living Room",
    room: "A big picture window with an ocean glare problem.",
  },
  {
    slug: "primary-bedroom",
    name: "Primary Bedroom",
    room: "Two double-hungs that let the 5am sun in.",
  },
  {
    slug: "farmhouse-kitchen",
    name: "Farmhouse Kitchen",
    room: "The sink window that bakes every afternoon.",
  },
  {
    slug: "home-office",
    name: "Home Office",
    room: "One window, all-day screen glare.",
  },
  {
    slug: "dining-bay",
    name: "Dining Room Bay",
    room: "A bay window that deserves better than blinds.",
  },
  {
    slug: "family-slider",
    name: "Family Room Slider",
    room: "A wide slider the old verticals never flattered.",
  },
];

/** Same 5 treatment states, same order, for every scene. */
export const SHOWROOM_TREATMENTS: ShowroomTreatment[] = [
  {
    slug: "bare",
    name: "Before",
    blurb: "The bare window, before Jim.",
  },
  {
    slug: "sheer-shades",
    name: "Silhouette Sheers",
    blurb: "Soft light, view preserved. Sunglasses for your windows.",
  },
  {
    slug: "honeycomb",
    name: "Duette Honeycomb",
    blurb: "Insulating cells. The warm-in-winter, dark-when-you-want choice.",
  },
  {
    slug: "shutters",
    name: "Plantation Shutters",
    blurb: "Built-in architecture. The one buyers ask for by name.",
  },
  {
    slug: "drapery",
    name: "Custom Drapery",
    blurb: "Tailored fabric, floor to ceiling. The finished-room look.",
  },
];

/** Canonical image path for a scene + treatment pairing. */
export function showroomImage(sceneSlug: string, treatmentSlug: string): string {
  return `/images/showroom/${sceneSlug}-${treatmentSlug}.jpg`;
}

/** Shared page copy for /virtual-showroom. */
export const SHOWROOM_COPY = {
  eyebrow: "The Virtual Showroom",
  h1: "See it in a room before you see Jim.",
  sub: "Six real rooms, five looks in each. Find the one you love and send it to Jim.",
  note: "Style preview. Your exact fabric and fit happen at the free consultation.",
  pickerHeading: "Pick your room.",
  pickerSub: "Six rooms, six light problems. Start with the one that looks like yours.",
  treatmentGroupLabel: "Treatment styles",
  sendCta: "Send this look to Jim",
  howItWorksHeading: "Three taps to a smarter consultation.",
  howItWorksSteps: [
    {
      emoji: "🛋️",
      title: "Pick your room",
      line: "Six real rooms, each with a light problem you will recognize.",
    },
    {
      emoji: "🪟",
      title: "Try every look",
      line: "Five treatments rendered in the same room, same window, same light.",
    },
    {
      emoji: "📨",
      title: "Send it to Jim",
      line: "Your favorite look rides along with your consultation request.",
    },
  ],
  formHeading: "Found the one? Jim brings the real sample.",
  formBody:
    "Your pick arrives attached to your request. Jim shows up with the actual fabric and gives you exact numbers at the free in-home consultation.",
} as const;
